### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 6DDUU6** [lgc-NB2Dev/nonebot-plugin-pingti#2]
nb run后一直循环报错这个，导致nonebot无法启动
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-pingti/assets/51308585/8f201e5c-1e12-4d41-b020-c76114ffb365)

**Comment by 6DDUU6** [comment]
找到了相关解决方法，但是不太会改
https://stackoverflow.com/questions/53724665/using-queues-results-in-asyncio-exception-got-future-future-pending-attached

**Comment by lgc2333** [comment]
v0.1.4
