### ISSUE TITLE
插件启动error

### ISSUE THREAD

**Issue by lin6953** [lgc-NB2Dev/nonebot-plugin-pingti#3]
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-pingti/assets/107689301/cb5a45db-65c5-4332-b2bc-fc259db9d6e0)

**Comment by lgc2333** [comment]
尝试降级 alc 版本至 1.8.3
```bash
pip install arclet-alconna==1.8.3
```

**Comment by lgc2333** [comment]
https://github.com/nonebot/plugin-alconna/releases/tag/v0.40.0rc1
